### PR TITLE
Added Makefile

### LINKED ISSUE #1111: [Request] to include libneocd_libretro.dll on the buildbot
Figured id get this in. Bparker said make a stink for inclusion here - so thats what im doing.

As per my other issue report on the RA issues tracker, the subsystem stuff ala playlist is incomplete and broken. Having this core in circumvents that issue entirely. Plus more options are a win.

https://github.com/libretro/neocd_libretro

for now i built it myself which caused issues with dependencies which left me having to build retroarch myself which leaves me without the ability to serial-update via stellar like I usually do.. SO youd be doing me a great personal service allowing me to return to regular updating with stellar and doing everyone else a service by having a core available that has no issues caused by subsystem AND includes chd support.

/lobby

### PR DESCRIPTION
**Pull request by gouchi**
- Should fix [#1111](https://github.com/libretro/libretro-super/issues/1111)
- Tested on Linux.

### CODE REVIEW

**Comment by fabrice-martinez** [comment]
Thanks a lot for this awesome contribution!
I've tested it successfully under Windows and Arch Linux with just a couple minor tweaks.
I'm going to test Raspi before merging.

**Comment by inactive123** [comment]
My bad for merging this prematurely @fabrice-martinez. You can either revert this or push followup commits in case something was missing. Either way is fine with me. Sorry about this.

**Comment by fabrice-martinez** [comment]
What is missing are FLAGS so CHD support understand 7zip, flac and so on are available.
It won't work properly without I think

**Comment by klepp0906** [comment]
was this shored up?  Assume not but want to make sure as it did post up on the buildbot, and its not loading for me so figured id check before i start the witch hunt ;p

**Comment by klepp0906** [comment]
nm figured out what was up.  core was named differently than last time I ran it.  made more in line w/ the rest of the bunch.   My playlist was incorrect.

all is well it seems.   Thank you guys very much <3

Still need a info file made up though /hide

Edit:
aaand the old info file was still hanging out.  named libneocd_libretro.   A rename and thats that.

but for future retroarcher's, probably want to get one of those merged into the BB however that works :P

**Pull request merged**
